http:
  middlewares:
    # anubis:
    #   forwardAuth:
    #     address: "http://anubis:8080/.within.website/x/cmd/anubis/api/check"

    redirect-www:
      redirectRegex:
        regex: "^https?://www\\.(.*)"
        replacement: "https://$1"
        permanent: true

    security-headers:
      headers:
        stsSeconds: 31536000
        stsIncludeSubdomains: true
        contentTypeNosniff: true
        browserXssFilter: true
